import type { Metadata } from 'next';
import { InterFont } from '@/fonts/font';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${InterFont.className} antialiased`}>{children}</body>
    </html>
  );
}
